<a href="https://colab.research.google.com/github/ArjunRai1/Deep_Learning_Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch as t
import numpy as np

Array to tensor

In [3]:
data = [[1,2],[3,4]]
x_data = t.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Numpy array to tensor


In [4]:
np_array = np.array(data)
x_np = t.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

Ones tensor

In [5]:
X_ones = t.ones_like(x_data)
print("ones tensor data:\n")
X_ones

ones tensor data:



tensor([[1, 1],
        [1, 1]])

Random tensor

In [6]:
X_rand = t.rand_like(x_data, dtype=t.float)
print("Random tensor:\n", X_rand)

Random tensor:
 tensor([[0.8830, 0.4346],
        [0.6483, 0.3805]])


Checking the attributes of a datatype and device on which they're stored


In [7]:
tensor = t.rand(3, 4)
print("Shape of tensor:", tensor.shape)
print("Datatype of tensor:", tensor.dtype)
print("Device of tensor:", tensor.device)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


From CPU to GPU


In [8]:
if t.cuda.is_available():
  tensor = tensor.to("cuda")
print("Now tensor is stored on: ", t.device)

Now tensor is stored on:  <class 'torch.device'>


Indexing and slicing

In [9]:
tensor = t.rand_like(x_data, dtype=t.float)
tensor

tensor([[0.2782, 0.0721],
        [0.9119, 0.5703]])

In [10]:
print("First row: ", tensor[0])
print("Last column: ", tensor[..., -1])

First row:  tensor([0.2782, 0.0721])
Last column:  tensor([0.0721, 0.5703])


HW question

In [35]:
tensor = t.tensor([[1,2,3,4],[4,5,6,7],[7,8,9,10]], dtype=t.float32)
print("First column:\n", tensor[..., 0])
print("Last Row:\n", tensor[-1, ...])
new_matrix = tensor[..., 0:3]
print("New matrix:\n", new_matrix)

First column:
 tensor([1., 4., 7.])
Last Row:
 tensor([ 7.,  8.,  9., 10.])
New matrix:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Concatenation

In [12]:
concat = t.cat([x_data, x_data], dim=1) #Dim 1 merges the first row of first matrix with first row of second matrix and it will be the first row of resultant matrix
concat

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [13]:
concat = t.cat([x_data, x_data], dim=0)
concat

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

Arithmetic operations

In [14]:
#Create tensors
x=t.tensor([1,2,3], dtype=t.float32)
y = t.tensor([4,5,6], dtype=t.float32)

In [15]:
#Addition
add = x+y
add

tensor([5., 7., 9.])

In [16]:
#Subtraction
sub = x-y
sub

tensor([-3., -3., -3.])

In [17]:
#Exponentiation
exponent = t.exp(x)
exponent

tensor([ 2.7183,  7.3891, 20.0855])

Square root and sin for x and y

In [18]:
#Square root
square_root = t.sqrt(x)
square_root

tensor([1.0000, 1.4142, 1.7321])

In [19]:
#Sin for x
sin = t.sin(x)
sin

tensor([0.8415, 0.9093, 0.1411])

In [20]:
#Sin for y
sin = t.sin(y)
sin

tensor([-0.7568, -0.9589, -0.2794])

Matrix Multiplication

In [21]:
matrix_A = t.tensor([[1,2],[3,4]], dtype = t.float32)
matrix_B = t.tensor([[5, 6], [7, 8]], dtype = t.float32)
result = t.matmul(matrix_A, matrix_B)
result

tensor([[19., 22.],
        [43., 50.]])

Find the determinant, transpose and inverse of a 3x3 matrix

In [28]:
#Determinant
matrix_A = t.tensor([[1,2],[3,4]], dtype = t.float32)
result = t.linalg.det(matrix_A)
result

tensor(-2.)

In [29]:
#Inverse
matrix_A = t.tensor([[5,6], [7,8]], dtype=t.float32)
result = t.linalg.inv(matrix_A)
result

tensor([[-4.0000,  3.0000],
        [ 3.5000, -2.5000]])

Eigen values and eigen vectors

In [31]:
#Transpose
matrix_A = t.tensor([[4,5], [6,7]], dtype=t.float32)
result = t.transpose(matrix_A, 0, 1)
result

tensor([[4., 6.],
        [5., 7.]])

In [24]:
eigenvalues, eigenvectors = t.linalg.eig(matrix_A) #Always returns two values
print("Eigen values:\n", eigenvalues)
print("Eigen vectors:\n", eigenvectors)

Eigen values:
 tensor([-0.3723+0.j,  5.3723+0.j])
Eigen vectors:
 tensor([[-0.8246+0.j, -0.4160+0.j],
        [ 0.5658+0.j, -0.9094+0.j]])


READING AN IMAGE

In [25]:
# @ is used for elementwise multiplication

In [26]:
from PIL import Image
import torchvision.transforms as transforms
import torch
#Specify the path to image file
image_path = "/content/pexels-jan-kroon-1038935.jpg"

#Open the image using PIL
image = Image.open(image_path)

#Define a transform to apply to the image(if needed)
transform = transforms.Compose([
    #Add any transformation needed, like resizing or normalization
    transforms.ToTensor(),  #Converts the image to pytorch tensor(important)
])

#apply the transform to the image
tensor_image = transform(image)

#Display the shape of tensor
print("Tensor shape: ", tensor_image.shape)

FileNotFoundError: [Errno 2] No such file or directory: '/content/pexels-jan-kroon-1038935.jpg'